export const UPSERT_STORE_GEOGRAPHY_SQL = `
  INSERT INTO plaappl."POG_STR_GEO" (
    "STR_NBR", "RETAIL_SQ_FT", "HR24_IND", "CITY_NAME", "STATE_CD",
    "ZIP_CD", "PHARMACY_IND", "ACTIVE_STORE_IND", "CLINIC_LINK_STORE_NBR",
    "MIN_CLINIC_IND", "PRIMARY_DC_ID", "WEB_SALE_PICKUP_LOCATION_IND",
    "DISTRICT_NBR", "STORE_OPEN_DT", "STORE_CLOSE_DT", "AREA_NBR",
    "REGION_NBR", "STREET_TXT"
  )
  VALUES %L
  ON CONFLICT ("STR_NBR") DO UPDATE SET
    "RETAIL_SQ_FT" = EXCLUDED."RETAIL_SQ_FT",
    "HR24_IND" = EXCLUDED."HR24_IND",
    "CITY_NAME" = EXCLUDED."CITY_NAME",
    "STATE_CD" = EXCLUDED."STATE_CD",
    "ZIP_CD" = EXCLUDED."ZIP_CD",
    "PHARMACY_IND" = EXCLUDED."PHARMACY_IND",
    "ACTIVE_STORE_IND" = EXCLUDED."ACTIVE_STORE_IND",
    "CLINIC_LINK_STORE_NBR" = EXCLUDED."CLINIC_LINK_STORE_NBR",
    "MIN_CLINIC_IND" = EXCLUDED."MIN_CLINIC_IND",
    "PRIMARY_DC_ID" = EXCLUDED."PRIMARY_DC_ID",
    "WEB_SALE_PICKUP_LOCATION_IND" = EXCLUDED."WEB_SALE_PICKUP_LOCATION_IND",
    "DISTRICT_NBR" = EXCLUDED."DISTRICT_NBR",
    "STORE_OPEN_DT" = EXCLUDED."STORE_OPEN_DT",
    "STORE_CLOSE_DT" = EXCLUDED."STORE_CLOSE_DT",
    "AREA_NBR" = EXCLUDED."AREA_NBR",
    "REGION_NBR" = EXCLUDED."REGION_NBR",
    "STREET_TXT" = EXCLUDED."STREET_TXT";
`;
